name: pillpal
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: any
  cloud_firestore: ^4.8.2
  firebase_auth: ^4.6.3
  google_sign_in: any
  google_fonts: any
  sizer: any
  rxdart: any
  provider: any
  shared_preferences: any
  timezone: any
  flutter_local_notifications: ^17.1.2
  flutter_datetime_picker: any
  permission_handler: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/icons/bottle.png
     - assets/icons/pill.png
     - assets/icons/syringe.png
     - assets/icons/tablet.png
     - assets/images/

  