// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZt56CV1_3Tl8hL7oHDVsuk1KcZzxsTR8',
    appId: '1:498876593168:web:c247b12988cad6a9a0c695',
    messagingSenderId: '498876593168',
    projectId: 'pillpal-48089',
    authDomain: 'pillpal-48089.firebaseapp.com',
    storageBucket: 'pillpal-48089.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLcAsk6Ss9VPrFLRVQt6NqqDTfVSJyhjQ',
    appId: '1:498876593168:android:611f728e166f1e5da0c695',
    messagingSenderId: '498876593168',
    projectId: 'pillpal-48089',
    storageBucket: 'pillpal-48089.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrMoUcT2Nby3kpqh7DyQyrPdGsYlGatIk',
    appId: '1:498876593168:ios:fe0ca9d407b26231a0c695',
    messagingSenderId: '498876593168',
    projectId: 'pillpal-48089',
    storageBucket: 'pillpal-48089.appspot.com',
    androidClientId: '498876593168-u6rkmr3buuhr39o71g3aktfqa4v038kk.apps.googleusercontent.com',
    iosClientId: '498876593168-5bf9cnsh61u712hb939uvvb6skm4j2nd.apps.googleusercontent.com',
    iosBundleId: 'com.example.pillpal',
  );
}
